version: '3.8'

services:
  app:
    build: ./docker/php
    container_name: meltapay_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php-fpm
    networks:
      - meltapay-network
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: meltapay_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - meltapay-network
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: meltapay_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: meltapay_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: habbpos   
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - meltapay-network

networks:
  meltapay-network:
    driver: bridge

volumes:
  dbdata:
